Repository ranghetto/Qovid, pull requests merged in 2022-04, with the labels that each got.

#16 Infect Behaviour
  Qovid.pro
  src/AI/ActorAI.cpp
  src/AI/ActorAI.h
  src/AI/InfectActorsInRange.cpp
  src/AI/InfectActorsInRange.h
  src/BehaviourTree/Selector.h
  src/BehaviourTree/Sequence.h
  src/Controllers/Simulation.cpp
  src/Controllers/Simulation.h
  src/Controllers/World.cpp
  src/Controllers/World.h
  src/Entities/Actor.cpp
  src/Entities/Actor.h
  src/main.cpp
Labels: enhancement

#29 5 controller simulazione
  Qovid.pro
  src/Controllers/Simulation.cpp
  src/Controllers/Simulation.h
  src/Controllers/World.cpp
  src/Controllers/World.h
  src/Views/ContainerWidget.cpp
  src/Views/ContainerWidget.h
  src/Views/InputWidget.cpp
  src/Views/InputWidget.h
  src/Views/MainWindow.cpp
  src/Views/MainWindow.h
  src/main.cpp
Labels: feature

#35 Bug fix vario
  Qovid.pro
  src/AI/CheckAlive.cpp
  src/AI/CheckAlive.h
  src/AI/CheckInfected.cpp
  src/AI/CheckInfected.h
  src/AI/InfectActorsInRange.cpp
  src/AI/InfectActorsInRange.h
  src/AI/Patrol.cpp
  src/AI/Patrol.h
  src/AI/RecoverDeath.cpp
  src/AI/RecoverDeath.h
  src/BehaviourTree/Node.cpp
  src/BehaviourTree/Node.h
  src/BehaviourTree/Selector.cpp
  src/BehaviourTree/Selector.h
  src/BehaviourTree/Sequence.h
  src/BehaviourTree/Tree.cpp
  src/BehaviourTree/Tree.h
  src/Controllers/Simulation.cpp
  src/Controllers/Simulation.h
  src/Controllers/World.cpp
  src/Controllers/World.h
  src/Entities/Actor.cpp
  src/Entities/Actor.h
  src/Views/ContainerWidget.cpp
  src/Views/ContainerWidget.h
  src/Views/InputWidget.cpp
  src/Views/InputWidget.h
  src/Views/MainWindow.cpp
  src/Views/MainWindow.h
  src/Views/SimulationView.cpp
  src/Views/SimulationView.h
  src/Views/SimulationWidget.cpp
  src/Views/SimulationWidget.h
  src/main.cpp
Labels: bug

#40 v0.0.1
  Qovid.pro
  src/AI/CheckAlive.cpp
  src/AI/CheckAlive.h
  src/AI/CheckInfected.cpp
  src/AI/CheckInfected.h
  src/AI/InfectActorsInRange.cpp
  src/AI/InfectActorsInRange.h
  src/AI/Patrol.cpp
  src/AI/Patrol.h
  src/AI/RecoverDeath.cpp
  src/AI/RecoverDeath.h
  src/BehaviourTree/Node.cpp
  src/BehaviourTree/Node.h
  src/BehaviourTree/Sequence.cpp
  src/BehaviourTree/Sequence.h
  src/BehaviourTree/Tree.cpp
  src/BehaviourTree/Tree.h
  src/Controllers/Simulation.cpp
  src/Controllers/Simulation.h
  src/Controllers/World.cpp
  src/Controllers/World.h
  src/Entities/Actor.cpp
  src/Entities/Actor.h
  src/Entities/Entity.h
  src/Views/ContainerWidget.cpp
  src/Views/ContainerWidget.h
  src/Views/InputWidget.cpp
  src/Views/InputWidget.h
  src/Views/MainWindow.cpp
  src/Views/MainWindow.h
  src/Views/SimulationWidget.cpp
  src/Views/SimulationWidget.h
  src/main.cpp
Labels: epic

#42 38 eliminazione singleton simulazione
  src/AI/CheckAlive.cpp
  src/AI/CheckAlive.h
  src/AI/CheckInfected.cpp
  src/AI/CheckInfected.h
  src/AI/InfectActorsInRange.cpp
  src/AI/InfectActorsInRange.h
  src/AI/Patrol.cpp
  src/AI/Patrol.h
  src/AI/RecoverDeath.cpp
  src/AI/RecoverDeath.h
  src/BehaviourTree/Node.h
  src/BehaviourTree/Sequence.cpp
  src/BehaviourTree/Sequence.h
  src/BehaviourTree/Tree.cpp
  src/BehaviourTree/Tree.h
  src/Controllers/Simulation.cpp
  src/Controllers/Simulation.h
  src/Entities/Actor.cpp
  src/Entities/Actor.h
  src/Entities/Entity.h
  src/Views/InputWidget.cpp
  src/Views/InputWidget.h
  src/main.cpp
Labels: refactor

#41 Fix morti che camminano
  src/AI/InfectActorsInRange.cpp
Labels: bug
